global using System.Data;
global using System.Linq;
global using System.Threading.Tasks;
global using System.Threading;
global using System;
global using Doka.NestedSet;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Xunit.Sdk;
global using Xunit;
global using Specifications = Doka.EntityFrameworkCore.NestedSet.Tests;
