// <auto-generated />

#nullable disable

namespace Doka.EntityFrameworkCore.NestedSet.Samples.Kpis.Migrations.Sqlite;

/// <summary>Provides the EF-generated target model for the initial hierarchy migration.</summary>
[DbContext(typeof(KpiSqliteContext))]
[Migration("20260929151217_InitialHierarchy")]
public partial class InitialHierarchy
{
    /// <inheritdoc />
    protected override void BuildTargetModel(
        ModelBuilder modelBuilder
    )
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("Doka:NestedSet:CollationsCaptured", true)
            .HasAnnotation("ProductVersion", "10.0.12");

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.Kpis.Kpi", b =>
        {
            b.Property<Guid>("NodeId")
                .HasColumnType("TEXT");

            b.Property<long>("End")
                .HasColumnType("INTEGER");

            b.Property<int>("Level")
                .HasColumnType("INTEGER");

            b.Property<Guid?>("ParentMetricId")
                .HasColumnType("TEXT");

            b.Property<Guid>("ProjectId")
                .HasColumnType("TEXT");

            b.Property<long>("SiblingPosition")
                .HasColumnType("INTEGER");

            b.Property<long>("Start")
                .HasColumnType("INTEGER");

            b.Property<int?>("SuccessfulDeployments")
                .HasColumnType("INTEGER");

            b.Property<string>("Title")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("TEXT");

            b.Property<Guid>("TreeId")
                .HasColumnType("TEXT");

            b.HasKey("NodeId");

            b.HasIndex("ProjectId", "ParentMetricId");

            b.HasIndex("ProjectId", "TreeId", "End")
                .HasDatabaseName("IX_NestedSet_654C58B4548D52B9D3D2FF9B");

            b.HasIndex("ProjectId", "TreeId", "Start")
                .HasDatabaseName("IX_NestedSet_0D3239B382B789AD6F29E1E1");

            b.HasIndex("ProjectId", "TreeId", "ParentMetricId", "SiblingPosition")
                .HasDatabaseName("IX_NestedSet_BA98001BADCB447C9F23278A");

            b.ToTable("Kpis", null, t =>
            {
                t.HasCheckConstraint("CK_NestedSet_DepthMin_1E494704C6EE", "\"Level\" >= 0");

                t.HasCheckConstraint("CK_NestedSet_LeftMin_B61E76BF6470", "\"Start\" >= 1");

                t.HasCheckConstraint("CK_NestedSet_PositionMin_9582FD621114", "\"SiblingPosition\" >= 0");

                t.HasCheckConstraint("CK_NestedSet_RightAfterLeft_F0F157FAE1F9", "\"End\" > \"Start\"");
            });

            b
                .HasAnnotation("Doka:NestedSet:Depth", "Level")
                .HasAnnotation("Doka:NestedSet:Left", "Start")
                .HasAnnotation("Doka:NestedSet:NodeKey", "NodeId")
                .HasAnnotation("Doka:NestedSet:Parent", "ParentMetricId")
                .HasAnnotation("Doka:NestedSet:Position", "SiblingPosition")
                .HasAnnotation("Doka:NestedSet:Right", "End")
                .HasAnnotation("Doka:NestedSet:Scope", "ProjectId")
                .HasAnnotation("Doka:NestedSet:TreeId", "TreeId")
                .HasAnnotation(
                    "Doka:NestedSet:TreeRegistryEntity",
                    "Doka.EntityFrameworkCore.NestedSet.TreeRegistry:Doka.EntityFrameworkCore.NestedSet.Samples.Kpis.Kpi"
                );
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.TreeRegistry:Doka.EntityFrameworkCore.NestedSet.Samples.Kpis.Kpi", b =>
        {
            b.Property<Guid>("Scope")
                .HasColumnType("TEXT");

            b.Property<Guid>("TreeId")
                .HasColumnType("TEXT");

            b.Property<byte>("Lifecycle")
                .HasColumnType("INTEGER");

            b.Property<long>("Revision")
                .HasColumnType("INTEGER");

            b.HasKey("Scope", "TreeId");

            b.ToTable("DokaNestedSetTrees_21E2E7888A7A36B0", (string)null);

            b.HasAnnotation("Doka:NestedSet:TreeRegistryOwner", "Doka.EntityFrameworkCore.NestedSet.Samples.Kpis.Kpi");
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.Kpis.Kpi", b =>
        {
            b.HasOne("Doka.EntityFrameworkCore.NestedSet.Samples.Kpis.Kpi", null)
                .WithMany()
                .HasForeignKey("ProjectId", "ParentMetricId")
                .HasPrincipalKey("ProjectId", "NodeId")
                .OnDelete(DeleteBehavior.Restrict);
        });
#pragma warning restore 612, 618
    }
}
