// <auto-generated />

#nullable disable

namespace Doka.EntityFrameworkCore.NestedSet.Samples.FileSystem.Migrations.Sqlite;

/// <summary>Provides the EF-generated target model for the initial hierarchy migration.</summary>
[DbContext(typeof(FileSystemSqliteContext))]
[Migration("20260929151108_InitialHierarchy")]
public partial class InitialHierarchy
{
    /// <inheritdoc />
    protected override void BuildTargetModel(
        ModelBuilder modelBuilder
    )
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("Doka:NestedSet:CollationsCaptured", true)
            .HasAnnotation("ProductVersion", "10.0.12");

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.FileSystem.Folder", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("Category")
                .IsRequired()
                .HasMaxLength(40)
                .HasColumnType("TEXT");

            b.Property<int>("Depth")
                .HasColumnType("INTEGER");

            b.Property<long>("Left")
                .HasColumnType("INTEGER");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("TEXT");

            b.Property<int?>("ParentId")
                .HasColumnType("INTEGER");

            b.Property<long>("Position")
                .HasColumnType("INTEGER");

            b.Property<long>("Right")
                .HasColumnType("INTEGER");

            b.Property<Guid>("TreeId")
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("ParentId");

            b.HasIndex("TreeId", "Left")
                .HasDatabaseName("IX_NestedSet_FC8D8DA800E92DF9B4480F36");

            b.HasIndex("TreeId", "Right")
                .HasDatabaseName("IX_NestedSet_A06121AD99644E6A50E54A72");

            b.HasIndex("TreeId", "ParentId", "Position")
                .HasDatabaseName("IX_NestedSet_A40159EE3BAF9A41CFAB0644");

            b.HasIndex("TreeId", "ParentId", "Name", "Category", "Id")
                .HasDatabaseName("IX_NestedSet_DF89A3C5B555AC38693139FE");

            b.ToTable("Folders", t =>
            {
                t.HasCheckConstraint("CK_NestedSet_DepthMin_D08AE90B5434", "\"Depth\" >= 0");

                t.HasCheckConstraint("CK_NestedSet_LeftMin_C427995A3819", "\"Left\" >= 1");

                t.HasCheckConstraint("CK_NestedSet_PositionMin_702D41AA53EE", "\"Position\" >= 0");

                t.HasCheckConstraint("CK_NestedSet_RightAfterLeft_6201912CB08F", "\"Right\" > \"Left\"");
            });

            b
                .HasAnnotation("Doka:NestedSet:Depth", "Depth")
                .HasAnnotation("Doka:NestedSet:Left", "Left")
                .HasAnnotation("Doka:NestedSet:NodeKey", "Id")
                .HasAnnotation("Doka:NestedSet:OrderDescending", new[] { false, false })
                .HasAnnotation("Doka:NestedSet:OrderMode", 0)
                .HasAnnotation("Doka:NestedSet:OrderNullSort", new[] { -1, -1 })
                .HasAnnotation("Doka:NestedSet:OrderProperties", new[] { "Name", "Category" })
                .HasAnnotation("Doka:NestedSet:Parent", "ParentId")
                .HasAnnotation("Doka:NestedSet:Position", "Position")
                .HasAnnotation("Doka:NestedSet:Right", "Right")
                .HasAnnotation("Doka:NestedSet:TreeId", "TreeId")
                .HasAnnotation(
                    "Doka:NestedSet:TreeRegistryEntity",
                    "Doka.EntityFrameworkCore.NestedSet.TreeRegistry:Doka.EntityFrameworkCore.NestedSet.Samples.FileSystem.Folder"
                );
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.TreeRegistry:Doka.EntityFrameworkCore.NestedSet.Samples.FileSystem.Folder", b =>
        {
            b.Property<Guid>("TreeId")
                .HasColumnType("TEXT");

            b.Property<byte>("Lifecycle")
                .HasColumnType("INTEGER");

            b.Property<long>("Revision")
                .HasColumnType("INTEGER");

            b.HasKey("TreeId");

            b.ToTable("DokaNestedSetTrees_CE8408B3FDD298F9", (string)null);

            b.HasAnnotation(
                "Doka:NestedSet:TreeRegistryOwner",
                "Doka.EntityFrameworkCore.NestedSet.Samples.FileSystem.Folder"
            );
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.FileSystem.Folder", b =>
        {
            b.HasOne("Doka.EntityFrameworkCore.NestedSet.Samples.FileSystem.Folder", null)
                .WithMany()
                .HasForeignKey("ParentId")
                .OnDelete(DeleteBehavior.Restrict);
        });
#pragma warning restore 612, 618
    }
}
