namespace Doka.EntityFrameworkCore.NestedSet.Tests.Sqlite;

/// <summary>Verifies SQLite-generated values after the final bulk-import structural writes.</summary>
public sealed class GeneratedValueTests : ProviderTest,
    IClassFixture<ProviderFixture<BulkGeneratedFixture, SqliteEngine>>
{
    private readonly BulkGeneratedFixture _fixture;

    /// <summary>Uses the SQLite fixture owning this suite's database resources.</summary>
    /// <param name="fixture">The provider fixture owned by this suite or its test collection.</param>
    public GeneratedValueTests(
        ProviderFixture<BulkGeneratedFixture, SqliteEngine> fixture
    ) : base(fixture)
    {
        _fixture = fixture.Value;
    }

    /// <summary>The detached imported result carries the token generated by its final structural SQL update.</summary>
    [Fact]
    public async Task ImportedNodeCanBeAttachedAndSavedWithRefreshedConcurrencyToken()
    {
        // Arrange
        await using var context = await _fixture.ResetAsync(Engine);
        var tree = context
            .NestedSet<BulkGeneratedNode>()
            .ForScope(7);

        var root = new BulkGeneratedNode { Name = "Root" };
        var child = new BulkGeneratedNode { Name = "Child" };
        var branch = new NestedSetBranch<BulkGeneratedNode>(root, [new NestedSetBranch<BulkGeneratedNode>(child)]);
        await tree.InsertForestAsync(
            [new NestedSetTreeImport<BulkGeneratedNode, Guid>(Guid.Empty, branch),],
            CancellationToken.None);

        var importedVersion = child.Version;
        var persistedVersion = await tree
            .InTree(Guid.Empty)
            .Nodes
            .Where(node => node.Id == child.Id)
            .Select(node => node.Version)
            .SingleAsync(CancellationToken.None);

        context.Attach(child);
        child.Name = "Renamed";

        // Act
        await context.SaveChangesAsync(CancellationToken.None);

        // Assert
        Assert.True(importedVersion > 0);
        Assert.Equal(persistedVersion, importedVersion);
        Assert.True(child.Version > importedVersion);
        Assert.Equal(
            child.Version,
            await tree
                .InTree(Guid.Empty)
                .Nodes
                .Where(node => node.Id == child.Id)
                .Select(node => node.Version)
                .SingleAsync(CancellationToken.None));
        Assert.Equal(
            "Renamed",
            await context
                .Set<BulkGeneratedNode>()
                .Where(node => node.Id == child.Id)
                .Select(node => node.Name)
                .SingleAsync(CancellationToken.None));
    }

    /// <summary>
    ///     Generated complex leaves are refreshed after parent and coordinate writes without payload reload.
    /// </summary>
    [Fact]
    public async Task ImportedComplexPayloadReflectsFinalGeneratedValues()
    {
        // Arrange
        await using var context = await _fixture.ResetAsync(Engine);
        var tree = context
            .NestedSet<BulkGeneratedNode>()
            .ForScope(7);

        var root = new BulkGeneratedNode { Name = "Root" };
        var child = new BulkGeneratedNode { Name = "Child" };
        var branch = new NestedSetBranch<BulkGeneratedNode>(root, [new NestedSetBranch<BulkGeneratedNode>(child)]);

        // Act
        await tree.InsertForestAsync(
            [new NestedSetTreeImport<BulkGeneratedNode, Guid>(Guid.Empty, branch),],
            CancellationToken.None);

        // Assert
        Assert.Equal("Generated detail", child.Details.Label);
        Assert.True(child.Details.Revision > 0);
        Assert.Equal(
            child.Details.Revision,
            await tree
                .InTree(Guid.Empty)
                .Nodes
                .Where(node => node.Id == child.Id)
                .Select(node => node.Details.Revision)
                .SingleAsync(CancellationToken.None));
        Assert.Empty(context.ChangeTracker.Entries());
    }
}
