// <auto-generated />

#nullable disable

namespace Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.Migrations.Sqlite;

/// <summary>Stores the EF-generated model for future migration comparisons.</summary>
[DbContext(typeof(UserGroupSqliteContext))]
partial class UserGroupSqliteContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("Doka:NestedSet:CollationsCaptured", true)
            .HasAnnotation("ProductVersion", "10.0.12");

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.Privilege", b =>
        {
            b.Property<Guid>("TenantId")
                .HasColumnType("TEXT");

            b.Property<string>("Code")
                .HasMaxLength(80)
                .HasColumnType("TEXT");

            b.HasKey("TenantId", "Code");

            b.ToTable("Privileges", (string)null);
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.Role", b =>
        {
            b.Property<Guid>("TenantId")
                .HasColumnType("TEXT");

            b.Property<Guid>("Id")
                .HasColumnType("TEXT");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("TEXT");

            b.Property<DateTime>("UpdatedAtUtc")
                .HasColumnType("TEXT");

            b.HasKey("TenantId", "Id");

            b.ToTable("Roles", (string)null);
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.RolePrivilege", b =>
        {
            b.Property<Guid>("TenantId")
                .HasColumnType("TEXT");

            b.Property<Guid>("RoleId")
                .HasColumnType("TEXT");

            b.Property<string>("PrivilegeCode")
                .HasMaxLength(80)
                .HasColumnType("TEXT");

            b.HasKey("TenantId", "RoleId", "PrivilegeCode");

            b.HasIndex("TenantId", "PrivilegeCode");

            b.ToTable("RolePrivileges", (string)null);
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.User", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<int>("Depth")
                .HasColumnType("INTEGER");

            b.Property<long>("Left")
                .HasColumnType("INTEGER");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("TEXT");

            b.Property<long>("NestedSetPosition")
                .HasColumnType("INTEGER");

            b.Property<string>("Position")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("TEXT");

            b.Property<long>("Right")
                .HasColumnType("INTEGER");

            b.Property<int?>("SupervisorId")
                .HasColumnType("INTEGER");

            b.Property<Guid>("TenantId")
                .HasColumnType("TEXT");

            b.Property<Guid>("TreeId")
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("TenantId", "SupervisorId");

            b.HasIndex("TenantId", "TreeId", "Left")
                .HasDatabaseName("IX_NestedSet_001BCAF47EB672AE55D4A418");

            b.HasIndex("TenantId", "TreeId", "Right")
                .HasDatabaseName("IX_NestedSet_CEAC656CDF8D8E7FF6AE0A82");

            b.HasIndex("TenantId", "TreeId", "SupervisorId", "NestedSetPosition")
                .HasDatabaseName("IX_NestedSet_38E1F10E9189DD3005AFB54E");

            b.ToTable("Users", null, t =>
            {
                t.HasCheckConstraint("CK_NestedSet_DepthMin_F03A5F16EC38", "\"Depth\" >= 0");

                t.HasCheckConstraint("CK_NestedSet_LeftMin_F767115F474D", "\"Left\" >= 1");

                t.HasCheckConstraint("CK_NestedSet_PositionMin_9BF8936D09D9", "\"NestedSetPosition\" >= 0");

                t.HasCheckConstraint("CK_NestedSet_RightAfterLeft_027293AE25EF", "\"Right\" > \"Left\"");
            });

            b
                .HasAnnotation("Doka:NestedSet:Depth", "Depth")
                .HasAnnotation("Doka:NestedSet:Left", "Left")
                .HasAnnotation("Doka:NestedSet:NodeKey", "Id")
                .HasAnnotation("Doka:NestedSet:Parent", "SupervisorId")
                .HasAnnotation("Doka:NestedSet:Position", "NestedSetPosition")
                .HasAnnotation("Doka:NestedSet:Right", "Right")
                .HasAnnotation("Doka:NestedSet:Scope", "TenantId")
                .HasAnnotation("Doka:NestedSet:TreeId", "TreeId")
                .HasAnnotation("Doka:NestedSet:TreeRegistryEntity", "Doka.EntityFrameworkCore.NestedSet.TreeRegistry:Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.User");
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.UserGroup", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<int>("Depth")
                .HasColumnType("INTEGER");

            b.Property<long>("Left")
                .HasColumnType("INTEGER");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("TEXT");

            b.Property<int?>("ParentId")
                .HasColumnType("INTEGER");

            b.Property<long>("Position")
                .HasColumnType("INTEGER");

            b.Property<long>("Right")
                .HasColumnType("INTEGER");

            b.Property<Guid>("TenantId")
                .HasColumnType("TEXT");

            b.Property<Guid>("TreeId")
                .HasColumnType("TEXT");

            b.Property<DateTime>("UpdatedAtUtc")
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("TenantId", "ParentId");

            b.HasIndex("TenantId", "TreeId", "Left")
                .HasDatabaseName("IX_NestedSet_3ACD4966042D5AD04BBA37F6");

            b.HasIndex("TenantId", "TreeId", "Right")
                .HasDatabaseName("IX_NestedSet_69CAAEEC5F26619C81245722");

            b.HasIndex("TenantId", "TreeId", "ParentId", "Position")
                .HasDatabaseName("IX_NestedSet_B4EBB8A364B521E6D7E941EB");

            b.ToTable("UserGroups", null, t =>
            {
                t.HasCheckConstraint("CK_NestedSet_DepthMin_FDB24289E574", "\"Depth\" >= 0");

                t.HasCheckConstraint("CK_NestedSet_LeftMin_BD623D388EE3", "\"Left\" >= 1");

                t.HasCheckConstraint("CK_NestedSet_PositionMin_27B996FE9A42", "\"Position\" >= 0");

                t.HasCheckConstraint("CK_NestedSet_RightAfterLeft_11FBC0D9D1D1", "\"Right\" > \"Left\"");
            });

            b
                .HasAnnotation("Doka:NestedSet:Depth", "Depth")
                .HasAnnotation("Doka:NestedSet:Left", "Left")
                .HasAnnotation("Doka:NestedSet:NodeKey", "Id")
                .HasAnnotation("Doka:NestedSet:Parent", "ParentId")
                .HasAnnotation("Doka:NestedSet:Position", "Position")
                .HasAnnotation("Doka:NestedSet:Right", "Right")
                .HasAnnotation("Doka:NestedSet:Scope", "TenantId")
                .HasAnnotation("Doka:NestedSet:TreeId", "TreeId")
                .HasAnnotation("Doka:NestedSet:TreeRegistryEntity", "Doka.EntityFrameworkCore.NestedSet.TreeRegistry:Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.UserGroup");
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.UserGroupMembership", b =>
        {
            b.Property<Guid>("TenantId")
                .HasColumnType("TEXT");

            b.Property<int>("UserId")
                .HasColumnType("INTEGER");

            b.Property<int>("UserGroupId")
                .HasColumnType("INTEGER");

            b.HasKey("TenantId", "UserId", "UserGroupId");

            b.HasIndex("TenantId", "UserGroupId", "UserId");

            b.ToTable("UserGroupMemberships", (string)null);
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.UserGroupRole", b =>
        {
            b.Property<Guid>("TenantId")
                .HasColumnType("TEXT");

            b.Property<int>("UserGroupId")
                .HasColumnType("INTEGER");

            b.Property<Guid>("RoleId")
                .HasColumnType("TEXT");

            b.HasKey("TenantId", "UserGroupId", "RoleId");

            b.HasIndex("TenantId", "RoleId");

            b.ToTable("UserGroupRoles", (string)null);
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.TreeRegistry:Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.User", b =>
        {
            b.Property<Guid>("Scope")
                .HasColumnType("TEXT");

            b.Property<Guid>("TreeId")
                .HasColumnType("TEXT");

            b.Property<byte>("Lifecycle")
                .HasColumnType("INTEGER");

            b.Property<long>("Revision")
                .HasColumnType("INTEGER");

            b.HasKey("Scope", "TreeId");

            b.ToTable("DokaNestedSetTrees_15640E0F343786E5", (string)null);

            b.HasAnnotation("Doka:NestedSet:TreeRegistryOwner", "Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.User");
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.TreeRegistry:Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.UserGroup", b =>
        {
            b.Property<Guid>("Scope")
                .HasColumnType("TEXT");

            b.Property<Guid>("TreeId")
                .HasColumnType("TEXT");

            b.Property<byte>("Lifecycle")
                .HasColumnType("INTEGER");

            b.Property<long>("Revision")
                .HasColumnType("INTEGER");

            b.HasKey("Scope", "TreeId");

            b.ToTable("DokaNestedSetTrees_CD53048DAAB2A93A", (string)null);

            b.HasAnnotation("Doka:NestedSet:TreeRegistryOwner", "Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.UserGroup");
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.RolePrivilege", b =>
        {
            b.HasOne("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.Privilege", null)
                .WithMany()
                .HasForeignKey("TenantId", "PrivilegeCode")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.Role", null)
                .WithMany()
                .HasForeignKey("TenantId", "RoleId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.User", b =>
        {
            b.HasOne("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.User", null)
                .WithMany()
                .HasForeignKey("TenantId", "SupervisorId")
                .HasPrincipalKey("TenantId", "Id")
                .OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.UserGroup", b =>
        {
            b.HasOne("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.UserGroup", null)
                .WithMany()
                .HasForeignKey("TenantId", "ParentId")
                .HasPrincipalKey("TenantId", "Id")
                .OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.UserGroupMembership", b =>
        {
            b.HasOne("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.UserGroup", null)
                .WithMany()
                .HasForeignKey("TenantId", "UserGroupId")
                .HasPrincipalKey("TenantId", "Id")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.User", null)
                .WithMany()
                .HasForeignKey("TenantId", "UserId")
                .HasPrincipalKey("TenantId", "Id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.UserGroupRole", b =>
        {
            b.HasOne("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.Role", null)
                .WithMany()
                .HasForeignKey("TenantId", "RoleId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("Doka.EntityFrameworkCore.NestedSet.Samples.UserGroups.UserGroup", null)
                .WithMany()
                .HasForeignKey("TenantId", "UserGroupId")
                .HasPrincipalKey("TenantId", "Id")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
        });
#pragma warning restore 612, 618
    }
}
